<a href="https://colab.research.google.com/github/cypherkrish/PythonDataScience/blob/main/02_DS_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy arrays

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [7]:
myarr = np.array(my_list)

In [13]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3], [4,5,6], [7, 8, 9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [27]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
len(np.linspace(0, 10, 21))

21

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random distributons of data

In [32]:
np.random.rand(1)

array([0.32224521])

In [34]:
np.random.rand(5, 2)

array([[0.38279598, 0.82584757],
       [0.23213173, 0.77136022],
       [0.65383388, 0.71698898],
       [0.83359363, 0.0514855 ],
       [0.96644304, 0.1790428 ]])

In [35]:
np.random.randn(10) # Returns standard normal distribution

array([-1.42276245,  0.39287416,  0.10100708, -2.04914621,  0.88687998,
       -0.39365424, -0.61021145,  0.74958939, -0.26354981, -0.6810562 ])

In [36]:
np.random.randn(10, 2)

array([[ 0.69700941,  1.18945526],
       [-0.22473863,  0.73180813],
       [-0.41195455,  1.25197087],
       [-0.21512606, -0.52113522],
       [-0.04566022,  1.4690786 ],
       [ 1.13532422,  0.26876881],
       [-0.27092205,  1.34194989],
       [-1.0105806 ,  0.2504745 ],
       [ 0.51701766,  0.71810084],
       [-1.65987564,  0.74515796]])

In [37]:
np.random.randint(0, 101, 5) # Random integers

array([57, 49, 10, 22, 49])

In [38]:
np.random.randint(0, 101, (4, 5)) # Random integers

array([[49, 21,  1, 91, 17],
       [27, 63, 85, 99, 94],
       [23, 92, 72, 32, 63],
       [34, 30, 17, 86,  9]])

In [39]:
# To reproduce the seed to have the constand reandom data

In [42]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
arr = np.arange(0, 25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
len(arr)

25

In [45]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0, 101, 10)

In [49]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [50]:
ranarr.max()

99

In [51]:
ranarr.min()

2

In [52]:
ranarr.argmax()

5

In [53]:
ranarr.argmin()

7

In [55]:
ranarr.dtype

dtype('int64')

In [56]:
arr.shape

(25,)

In [57]:
arr = arr.reshape(5, 5)

In [58]:
arr.shape

(5, 5)

In [59]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [60]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Indexing

In [61]:
arr = np.arange(0, 11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[8]

8

In [64]:
arr[1:5]

array([1, 2, 3, 4])

In [65]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [66]:
arr[:5]

array([0, 1, 2, 3, 4])

In [67]:
arr[5:8]

array([5, 6, 7])

In [68]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr[0:5] = 100  # Broadcasting operation

In [78]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
arr = np.arange(0, 11)

In [80]:
slice_of_arr = arr[0:5]

In [81]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [82]:
slice_of_arr[:] = 99 # Broadcasting operation

In [83]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [84]:
# use the copy method

In [85]:
arr_copy = arr.copy()

In [86]:
v

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [87]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [88]:
arr_copy[0:5] = 100

In [89]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [90]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [92]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [94]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [95]:
arr_2d.shape

(3, 3)

In [96]:
arr_2d[0]

array([ 5, 10, 15])

In [98]:
arr_2d[2]

array([35, 40, 45])

In [103]:
arr_2d[1][1]

25

In [104]:
arr_2d[1,1]

25

In [105]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [107]:
arr_2d[:, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [108]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [109]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [110]:
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [111]:
# Conditonal selection

In [113]:
arr = np.arange(0, 11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [116]:
bool_arr = arr > 4

In [118]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [119]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [120]:
arr [arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [123]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [126]:
len(dice_rolls[ dice_rolls > 2])

19

#NumPy Operations

In [127]:
arr = np.arange(0, 10)

In [128]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [130]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [131]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [135]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [136]:
arr / arr

<ipython-input-136-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [137]:
1 / 0

ZeroDivisionError: ignored

In [138]:
1 /arr

<ipython-input-138-148a20bab727>:1: RuntimeWarning: divide by zero encountered in divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [139]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [140]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [141]:
np.log(arr)

<ipython-input-141-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Summary Statistics

In [142]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr.sum()

45

In [144]:
arr.mean()

4.5

In [145]:
arr.max()

9

In [146]:
arr.min()

0

In [147]:
arr.var()

8.25

In [148]:
arr.std()

2.8722813232690143

In [150]:
arr_2d_arr = np.arange(0, 25).reshape(5, 5)

In [151]:
arr_2d_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
arr_2d_arr.sum()

300

In [155]:
arr_2d_arr.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [156]:
arr_2d_arr.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

Example

In [157]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])


In [159]:
account_total = account_transactions.sum()

# Examples